services:
  mineru:
    image: mineru:v1.3.3
    container_name: mineru
    runtime: nvidia
    ports:
      - "8752:8752"
    volumes:
      - /data/ssd1/mineru/doc-ingester:/app
      - /data/ssd1/mineru/model/slanet-plus.onnx:/opt/conda/lib/python3.10/site-packages/rapid_table/models/slanet-plus.onnx
      - /data/ssd1/mineru/model/mineru_models/magic-pdf.json:/root/magic-pdf.json
      - /data/ssd1/mineru/model/mineru_models/.cache/huggingface:/root/.cache/huggingface
      - /data/ssd1/mineru/model/mineru_models/.cache/tiktoken:/root/.cache/tiktoken
      - /data/ssd1/mineru/model/result:/app/result
    devices:
      - /dev/nvidia-uvm
      - /dev/nvidia-uvm-tools
      - /dev/nvidia-modeset
      - /dev/nvidiactl
      - /dev/nvidia7
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      #- http_proxy=http://proxy2.tao.inventec:3128
      #- https_proxy=http://proxy2.tao.inventec:3128      
    stdin_open: true
    tty: true
    command: python startup.py
